{% set name = "hyperlib" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hyperlib-{{ version }}.tar.gz
  sha256: 6b9dc939287bbd6a0a18ceb0a1f3763acf26f3bbfd147ea488dc2db250ad8a5e

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37 or win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - pybind11 >=2.7.0
    - python
  run:
    - gmpy2
    - mpmath
    - networkx
    - numpy >=1.19.3
    - pybind11 >=2.7.0
    - python
    - scipy >=1.7.0
    - tensorflow >=2.0.0

test:
  imports:
    - hyperlib
  commands:
    - pip check
  requires:
    - pip
    - pybind11 >=2.7.0

about:
  home: https://github.com/nalexai/hyperbolic
  summary: Machine learning components in the hyperbolic space
  license: MIT
  license_file: LICENSE
  description: |
    This library implements common Neural Network components in the hypberbolic
     space (using the Poincare model). The implementation of this library uses
     Tensorflow as a backend and can easily be used with Keras and is meant to
     help Data Scientists, Machine Learning Engineers, Researchers and others to
     implement hyperbolic neural networks. You can also use this library for
     uses other than neural networks by using the mathematical functions
     available in the Poincare class. In the future we may implement components
     that can be used in models other than neural networks.

extra:
  recipe-maintainers:
    - thewchan
